### ISSUE TITLE
Integration with Bare Metal Nomad

### ISSUE THREAD

**Issue by valafon** [spegel-org/spegel#672] opened 2024-12-19 06:13 UTC
### Describe the problem to be solved

Hello, dear community,

Could you please advise if it’s possible to adapt this solution for Nomad on our own? For example, by building the code or Docker images and running it in Nomad (either as jobs or as systemd units on nodes) so that it works similarly to how it does with Kubernetes. Has anyone had such an experience?

Thank you in advance!

**Comment by phillebaba** [comment] 2024-12-20 22:52
This seems like it is a duplicate of #303 which was discussed earlier. I did some work there trying to figure out how to get things working but eventually gave up mostly due to time constraints. The first hurdle is to chose the correct driver, as you either need to use the Containerd driver or the Docker driver configured with Containerd as the image store. Then you need to figure out how to get the correct networking working, which is where I stopped due to time. I think the biggest challenge is that every Nomad cluster seems to be a bit different networking wise etc.

I will close this issue so we can keep all Nomad discussions in a single issue, so it would be great if you could continue it there. I am not opposed to figuring out how to support Nomad, I just don't use it so I don't have the background to document it quickly.

**Closed by phillebaba** 2024-12-20 22:52 UTC
Labels: enhancement
