### ISSUE TITLE
Failed scheduled image state updater is causing high cpu load on spegel and containerd

### ISSUE THREAD

**Issue by ugur99** [spegel-org/spegel#444] opened 2024-04-18 11:36 UTC
### Spegel version

v0.0.18

### Kubernetes distribution

Kubespray

### Kubernetes version

v1.26.10

### CNI

Cilium

### Describe the bug

Some of the spegel pods in the cluster are getting the following error after the initialization of the pod; and this constant error seems like causing to increased cpu consumption on the containerd and spegel side. After disabling spegel on these nodes; containerd cpu usage is backing to the normal values again.

* About the problem: We checked the similar problem described in [here](https://github.com/spegel-org/spegel/issues/172); and deleted related file `/var/lib/containerd/io.containerd.content.v1.content/blobs/sha256/fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5`. But the error still persists. In that case how can we troubleshoot it further; and how can we solve this problem.

* About cpu load on containerd: It seems that there is a correlation between the cpu spikes and this error; and this breaks containerd from functioning. Can we prevent this in such cases?
 
```
 configuration {"level":"info","ts":1713439195.3878322,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://harbor.test.dev","path":"/etc/containerd/certs.d/harbor.test.dev/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3881152,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://docker.io","path":"/etc/containerd/certs.d/docker.io/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3882353,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://ghcr.io","path":"/etc/containerd/certs.d/ghcr.io/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3883452,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://quay.io","path":"/etc/containerd/certs.d/quay.io/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3884552,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://mcr.microsoft.com","path":"/etc/containerd/certs.d/mcr.microsoft.com/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3885758,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://public.ecr.aws","path":"/etc/containerd/certs.d/public.ecr.aws/hosts.toml"}
 configuration {"level":"info","ts":1713439195.388685,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://gcr.io","path":"/etc/containerd/certs.d/gcr.io/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3887906,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://registry.k8s.io","path":"/etc/containerd/certs.d/registry.k8s.io/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3888988,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://k8s.gcr.io","path":"/etc/containerd/certs.d/k8s.gcr.io/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3890042,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://lscr.io","path":"/etc/containerd/certs.d/lscr.io/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3891098,"caller":"oci/containerd.go:520","msg":"added containerd mirror configuration","registry":"https://nvcr.io","path":"/etc/containerd/certs.d/nvcr.io/hosts.toml"}
 configuration {"level":"info","ts":1713439195.3891716,"caller":"build/main.go:85","msg":"gracefully shutdown"}
 registry {"level":"info","ts":1713439195.9999304,"caller":"build/main.go:194","msg":"running Spegel","registry":":5000","router":":5001"}
 registry {"level":"info","ts":1713439196.00065,"caller":"state/state.go:43","msg":"running scheduled image state update"}
-  › configuration
 registry {"level":"info","ts":1713439196.0009518,"logger":"p2p","caller":"routing/p2p.go:122","msg":"starting p2p router","id":"/ip4/10.235.185.61/tcp/5001/p2p/12D3KooWRCPPf6VeaiT2t6cQYPoxUx2atmFWwbNDcit3XbaH49kC"}
 registry {"level":"info","ts":1713439196.0011628,"caller":"leaderelection/leaderelection.go:245","msg":"attempting to acquire leader lease spegel/test-spegel-leader-election...\n"}
 registry {"level":"error","ts":1713439197.065989,"caller":"state/state.go:26","msg":"restarting image state tracker due to error","error":"received errors when updating all images: could not get digests for image harbor.test.dev/test/test-frontend@sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5: failed to walk image manifests: unexpected media type application/octet-stream for digest: sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5","stacktrace":"github.com/xenitab/spegel/pkg/state.Track\n\t/build/pkg/state/state.go:26\nmain.registryCommand.func5\n\t/build/main.go:168\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}
 registry {"level":"info","ts":1713439197.0661466,"caller":"state/state.go:43","msg":"running scheduled image state update"}
 registry {"level":"error","ts":1713439198.139312,"caller":"state/state.go:26","msg":"restarting image state tracker due to error","error":"received errors when updating all images: could not get digests for image harbor.test.dev/test/test-frontend@sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5: failed to walk image manifests: unexpected media type application/octet-stream for digest: sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5","stacktrace":"github.com/xenitab/spegel/pkg/state.Track\n\t/build/pkg/state/state.go:26\nmain.registryCommand.func5\n\t/build/main.go:168\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}
 registry {"level":"info","ts":1713439198.13943,"caller":"state/state.go:43","msg":"running scheduled image state update"}
 registry {"level":"error","ts":1713439199.107945,"caller":"state/state.go:26","msg":"restarting image state tracker due to error","error":"received errors when updating all images: could not get digests for image harbor.test.dev/test/test-frontend@sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5: failed to walk image manifests: unexpected media type application/octet-stream for digest: sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5","stacktrace":"github.com/xenitab/spegel/pkg/state.Track\n\t/build/pkg/state/state.go:26\nmain.registryCommand.func5\n\t/build/main.go:168\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}
 registry {"level":"info","ts":1713439199.1080744,"caller":"state/state.go:43","msg":"running scheduled image state update"}
 registry {"level":"error","ts":1713439200.134552,"caller":"state/state.go:26","msg":"restarting image state tracker due to error","error":"received errors when updating all images: could not get digests for image harbor.test.dev/test/test-frontend@sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5: failed to walk image manifests: unexpected media type application/octet-stream for digest: sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5","stacktrace":"github.com/xenitab/spegel/pkg/state.Track\n\t/build/pkg/state/state.go:26\nmain.registryCommand.func5\n\t/build/main.go:168\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}
 registry {"level":"info","ts":1713439200.1346736,"caller":"state/state.go:43","msg":"running scheduled image state update"}
 registry {"level":"error","ts":1713439201.1686144,"caller":"state/state.go:26","msg":"restarting image state tracker due to error","error":"received errors when updating all images: could not get digests for image harbor.test.dev/test/test-frontend@sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5: failed to walk image manifests: unexpected media type application/octet-stream for digest: sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5","stacktrace":"github.com/xenitab/spegel/pkg/state.Track\n\t/build/pkg/state/state.go:26\nmain.registryCommand.func5\n\t/build/main.go:168\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}
 registry {"level":"info","ts":1713439201.1687543,"caller":"state/state.go:43","msg":"running scheduled image state update"}
 registry {"level":"error","ts":1713439202.090724,"caller":"state/state.go:26","msg":"restarting image state tracker due to error","error":"received errors when updating all images: could not get digests for image harbor.test.dev/test/test-frontend@sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5: failed to walk image manifests: unexpected media type application/octet-stream for digest: sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5","stacktrace":"github.com/xenitab/spegel/pkg/state.Track\n\t/build/pkg/state/state.go:26\nmain.registryCommand.func5\n\t/build/main.go:168\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}
 registry {"level":"info","ts":1713439202.0909104,"caller":"state/state.go:43","msg":"running scheduled image state update"}
 registry {"level":"error","ts":1713439203.0864813,"caller":"state/state.go:26","msg":"restarting image state tracker due to error","error":"received errors when updating all images: could not get digests for image harbor.test.dev/test/test-frontend@sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5: failed to walk image manifests: unexpected media type application/octet-stream for digest: sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5","stacktrace":"github.com/xenitab/spegel/pkg/state.Track\n\t/build/pkg/state/state.go:26\nmain.registryCommand.func5\n\t/build/main.go:168\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}
 registry {"level":"info","ts":1713439203.0870545,"caller":"state/state.go:43","msg":"running scheduled image state update"}
```

![image](https://github.com/spegel-org/spegel/assets/57688057/80a2d3c0-d6ef-4a92-9bfc-e34608b08636) 
![image](https://github.com/spegel-org/spegel/assets/57688057/0295a8fa-4279-4ba2-8f9f-36e74b9ed287)

**Comment by phillebaba** [comment] 2024-04-18 14:30
The CPU usage issues spiking is probably caused by an issue that was fixed in #371, could you update to the latest Spegel version to see if the problems persist?

The root cause is still something to do with something wrong with the image walking. Would it be possible to share an example image that is causing this error?

**Comment by ugur99** [comment] 2024-04-19 10:14
hey @phillebaba thanks for the quick response! And yes; last release fixed the cpu problem on our side. 

I'm afraid it's not possible to share the image due to confidentiality, but we'd be happy to assist you if there's anything we can inspect on it. Is there anything you suspect that you would like us to look into?
> The root cause is still something to do with something wrong with the image walking. Would it be possible to share an example image that is causing this error?

**Comment by phillebaba** [comment] 2024-04-19 11:50
I understand that you cant share the image. Do you know if you are building images in an unusual way or adding additional data to the manifest. I know that error you are seeing originates from here.

https://github.com/spegel-org/spegel/blob/a2bd6ce16f5a4726e97db8da430f6e77ae6aa831/pkg/oci/containerd.go#L253-L254

This may be wrong and we should maybe ignore unknown manifests instead. I just want to add a similar image as a test case to verify that things will be resolved. If possible could you share the contents of the layer referencing the layer `sha256:fad63c8d1e5a7eda393aeda714dcc3b76a55f0334a7d73b600d9b2b208a2dae5`. This would most likely be the index  or the manifest for the image.

**Comment by phillebaba** [comment] 2024-05-07 20:39
Closing this issue as the issue has been resolved in a release.

@ugur99 please open a new issue if you are facing issues with walking the image.

**Closed by phillebaba** 2024-05-07 20:39 UTC
Labels: bug

**Comment by ugur99** [comment] 2024-05-07 21:02
thanks for the support @phillebaba!
