### ISSUE TITLE
Getting high volumes of 404 and 500 errors. Any insight?

### ISSUE THREAD

**Issue by tyu0912** [spegel-org/spegel#469] opened 2024-05-08 20:32 UTC
### Spegel version

v0.0.22

### Kubernetes distribution

EKS

### Kubernetes version

1.29.0

### CNI

AWS VPC CNI

### Describe the bug

_**UPDATE 1:**_ After some further investigation, it seems that adding my team's internal ECR registry caused a rise in errors and performance to degrade a bit (below). Seems like things aren't going as they should be...  wondering what's happening and how to fix...🤔 

---

Hello, apologies if this is very simple. I'm new to this tool. I just deployed Spegel after modifying the containerd settings in my EKS cluster according to the compatibility guide here: https://github.com/spegel-org/spegel/blob/main/docs/COMPATIBILITY.md.

The pods are running so I think on some levels it is working according to https://github.com/spegel-org/spegel/blob/main/docs/FAQ.md but I noticed that when a new node comes up I am getting a lot of 404/500 errors which leads to believe the mirroring isn't working as expected. I'm not familiar with what these errors indicate. Is this normal?

I did find https://github.com/spegel-org/spegel/issues/217 but not sure if it's related. Using `containerd config dump`, confirmed the settings should be ok.

```
sh-4.2$ containerd config dump | grep config_path -B 5

    [plugins."io.containerd.grpc.v1.cri".image_decryption]
      key_model = "node"

    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d:/etc/docker/certs.d"
```

```
sh-4.2$ containerd config dump | grep discard_unpacked_layers -B 5
      setup_serially = false

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      disable_snapshot_annotations = true
      discard_unpacked_layers = false
```

Any insight is much appreciated! Thank you. 😄 

Error 1
```
{"time":"2024-05-08T20:28:40.362320827Z","level":"ERROR","source":{"function":"github.com/spegel-org/spegel/pkg/registry.(*Registry).handle.func1","file":"/build/pkg/registry/registry.go","line":135},"msg":"","err":"content digest sha256:1e3d9b7d145208fa8fa3ee1c9612d0adaac7255f1bbc9ddea7e461e0b317805c: not found","path":"/v2/jimmidyson/configmap-reload/blobs/sha256:1e3d9b7d145208fa8fa3ee1c9612d0adaac7255f1bbc9ddea7e461e0b317805c","status":500,"method":"GET","latency":"574.095µs","ip":"<some-ip>"}
```

Error 2
```
{"time":"2024-05-08T20:28:39.25413767Z","level":"ERROR","source":{"function":"github.com/spegel-org/spegel/pkg/registry.(*Registry).handleMirror.func1","file":"/build/pkg/registry/registry.go","line":272},"msg":"proxy failed attempting next","key":"sha256:fe5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58","path":"/v2/jimmidyson/configmap-reload/blobs/sha256:fe5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58","ip":"<some-ip>","err":"expected mirror to respond with 200 OK but received: 500 Internal Server Error"}
```

Error 3
```
{"time":"2024-05-08T20:28:36.85743246Z","level":"ERROR","source":{"function":"github.com/spegel-org/spegel/pkg/registry.(*Registry).handle.func1","file":"/build/pkg/registry/registry.go","line":135},"msg":"","err":"request closed for key: sha256:566294b429823a40b102147b6742390ede89f1f30f9dd6c1f742aae4defe4504","path":"/v2/jetstack/cert-manager-webhook/blobs/sha256:566294b429823a40b102147b6742390ede89f1f30f9dd6c1f742aae4defe4504","status":404,"method":"GET","latency":"5.021653989s","ip":"<some-ip>"}
```

**Comment by tyu0912** [comment] 2024-05-08 21:22
OK, so most of the 500 errors disappeared after I added some more registries. Should've caught that! I am still getting a few 404s though. Are these normal?  Example below:

```
{"time":"2024-05-08T21:19:19.740555437Z","level":"ERROR","source":{"function":"github.com/spegel-org/spegel/pkg/registry.(*Registry).handle.func1","file":"/build/pkg/registry/registry.go","line":135},"msg":"","err":"request closed for key: <registry>/<image-tag>","path":"<the-path>","status":404,"method":"HEAD","latency":"5.001274834s","ip":"10.2.116.31"}
```

**Comment by bittrance** [comment] 2024-05-08 21:23
The 404 should not really be at error level, but the logging is a bit simplistic. That is just Spegel telling the caller that it cannot help and that the caller should try the next configured mirror for that registry, so that is in some sense normal.

**Comment by tyu0912** [comment] 2024-05-08 21:32
Thanks @bittrance . That's reassuring. Out of curiosity, do you know about this one too? `expected mirror to respond with 200 OK but received: 500 Internal Server Error` . Did another take and these ones seem to spike  every so often. 

![image](https://github.com/spegel-org/spegel/assets/24836159/79601166-2445-4a71-afcf-5f8d25f20696)


```
{"time":"2024-05-08T20:28:39.25413767Z","level":"ERROR","source":{"function":"github.com/spegel-org/spegel/pkg/registry.(*Registry).handleMirror.func1","file":"/build/pkg/registry/registry.go","line":272},"msg":"proxy failed attempting next","key":"sha256:fe5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58","path":"/v2/jimmidyson/configmap-reload/blobs/sha256:fe5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58","ip":"<some-ip>","err":"expected mirror to respond with 200 OK but received: 500 Internal Server Error"}
```

**Comment by tyu0912** [comment] 2024-05-08 21:36
Maybe it's normal actually? The msg does say `proxy failed attempting next`. Curious why it's failing though... is it just because the layer is not found? 🤔

**Comment by bittrance** [comment] 2024-05-08 21:39
We had reports of the "expected 200 but was 500" before. I *think* those errors implies that the Spegel cluster is internally inconsistent. I think the error occurs because some Spegel node advertised the blob hash, but when the acting mirror proxied the request to it, it errored. I'm not sure whether that is exactly an error or just eventual consistency in action.

In your errors above, is it possible that Error 1 on one node could be resulting in Error 2 on another node? The timestamps suggests not, but maybe they are for different requests?

**Comment by tyu0912** [comment] 2024-05-08 22:16
Wondering if your theory on eventual consistency is correct. It does seem the errors are dying down a bit now.  
![image](https://github.com/spegel-org/spegel/assets/24836159/83456a67-4ff3-4307-87af-1cb16b4c16dd)

The way I'm doing the containerd update is through daemonsets. Is it possible that there's some kind of race condition overlap here where the node already has some container layers from other services before containerd restarts?

**Comment by tyu0912** [comment] 2024-05-08 23:44
Another interesting observation. It seems I'm not getting the best performance either... Below is a graph of `kube_pod_status_ready_time` - `kube_pod_status_scheduled_time`. After I added my teams internal ECR registry ~5:30pm we can see the increased activity for the various pods. Eyeballing the average it seems a bit higher than before I started implementing Spegel. It is also around this time as well when the spike in error logs showed up. 

![image](https://github.com/spegel-org/spegel/assets/24836159/16d70ef1-92e5-49c2-9692-7d8d1b7b8864)

**Comment by phillebaba** [comment] 2024-05-09 14:32
I will start off by clarifying something about the Spegel. It is a best effort cache, meaning that images may or may not exist on other nodes when and image is pulled. On top of that images may not be discovered due to the distributed nature of the DHT.

Having said that I do not think that this is an issue that you are facing. I made some changes before v0.0.22 to make sure that 404 are returned when an image is not found and 500 errors are returned for other types of errors. The error `content digest sha256:ce9698c36317f0d048a2e692511e8a1ec371fa047493b809f71efe3af526b366: not found` that you are seeing is interesting however. This means that traffic is being routed to the node but the node is not able to find the layer. 

I saw that you wrote that the errors seems to come specifically from images pulled from ECR. I am not sure why this would be the case, but there might be something specific that is done when EKS pulls images from ECR?

Could you share your values configuration used to deploy Spegel?

**Comment by tyu0912** [comment] 2024-05-09 17:11
> I will start off by clarifying something about the Spegel. It is a best effort cache, meaning that images may or may not exist on other nodes when and image is pulled. On top of that images may not be discovered due to the distributed nature of the DHT.

Understood. Thanks for clarifying @phillebaba 

> I saw that you wrote that the errors seems to come specifically from images pulled from ECR. I am not sure why this would be the case, but there might be something specific that is done when EKS pulls images from ECR?

That sounds plausible to me. Here are my values. Appreciate the help!

```
serviceMonitor:
  enabled: true

spegel:
  registries:
    - https://cgr.dev
    - https://docker.io
    - https://ghcr.io
    - https://quay.io
    - https://mcr.microsoft.com
    - https://public.ecr.aws
    - https://gcr.io
    - https://registry.k8s.io
    - https://k8s.gcr.io
    - https://lscr.io
    - https://<my-account-number>.dkr.ecr.<my-region>.amazonaws.com
```

**Comment by danielloader** [comment] 2024-05-18 12:30
Have you applied the userData patch to the EKS nodes so that containerd keeps the intermediate layers after a pull?

**Comment by danielsand** [comment] 2024-05-21 09:12
joining the fun.

---
{"time":"2024-05-21T11:06:31.240376472+02:00","level":"ERROR","source":{"function":"github.com/spegel-org/spegel/pkg/registry.(*Registry).handleMirror.func1","file":"/build/pkg/registry/registry.go","line":272},"msg":"proxy failed attempting next","key":"sha256:e006012862ce06d8bdbba2a6a1ddc0d2eb5cb2fa6565e1500ed58dc016bde00a","path":"/v2/nfd/node-feature-discovery/blobs/sha256:e006012862ce06d8bdbba2a6a1ddc0d2eb5cb2fa6565e1500ed58dc016bde00a","ip":"<REDACTED>","err":"expected mirror to respond with 200 OK but received: 500 Internal Server Error"}
{"time":"2024-05-21T11:06:31.242107206+02:00","level":"ERROR","source":{"function":"github.com/spegel-org/spegel/pkg/registry.(*Registry).handleMirror.func2","file":"/build/pkg/registry/registry.go","line":277},"msg":"mirror failed attempting next","key":"sha256:e006012862ce06d8bdbba2a6a1ddc0d2eb5cb2fa6565e1500ed58dc016bde00a","path":"/v2/nfd/node-feature-discovery/blobs/sha256:e006012862ce06d8bdbba2a6a1ddc0d2eb5cb2fa6565e1500ed58dc016bde00a","ip":"<REDACTED>","err":"expected mirror to respond with 200 OK but received: 500 Internal Server Error"}
---

Hunch note:
github might be the issue (rate limited) - but im not able to verify it currently.

**Comment by thockin** [comment] 2024-05-21 14:44
registry.k8s.io does not offer a fixed list of backend - if you need to filter aggressively, you need to pull from a mirror you control.

**Comment by BenTheElder** [comment] 2024-05-21 16:37
https://registry.k8s.io#stability has pointers to mirroring guides and other details.

**Comment by phillebaba** [comment] 2024-05-21 17:12
I do not understand how changing DNS settings would affect Spegel. Spegel is a best effort mirror that does not do any upstream requests to any other registries. This specific `expected mirror to respond with 200 OK but received: 500 Internal Server Error` just means that a request was forwarded to a node that should have had the layer but did not. This may be caused by some internal Containerd errors, or because the layer actually does not exist on disk.

I refactored the logging in #488 and am working on #494 to help users understand a bit better what is going on when they see an error. 

I was hoping to get #472 done before the next release but that has been blocked due to some account access preventing me from running the benchmarks. So might just cut a release now to see if the update error logs gives some more insight into the actual problem.

**Comment by danielsand** [comment] 2024-05-22 11:35
@phillebaba

The 500 will most likely show up at the point when spegel checks for the S3 buckets hosting the container image blob pointers and landed on my end in an DNS error. 

It's further down the road code wise.

and for the other comments.... yeah the "DOH ! READ DOCS  !!11" signs are visible. 

For a public K8S OCI registry the security of this setup is questionable at best. (supply chain) 
it is what it is

cheers

**Comment by phillebaba** [comment] 2024-07-11 20:51
Closing as this issue has been used to discuss different topics and has low activity. Please open a new issue for future discussions.

**Closed by phillebaba** 2024-07-11 20:51 UTC
Labels: bug
