### ISSUE TITLE
Local mirror spend more time than remote download for large image

### ISSUE THREAD

**Issue by sonyafenge** [spegel-org/spegel#378] opened 2024-03-01 05:29 UTC
### Spegel version

v0.0.17

### Kubernetes distribution

kubeadm

### Kubernetes version

v1.26.7

### CNI

Calico

### Describe the bug

local mirror download will take more time than remote download image
Repro steps:
1. kubeadm create cluster with 2 worker nodes 
2. install spegel using helm chart 
3. apply a pods yaml with 10GB image to worker-node1, using 3m50s to pulling image
```
Every 2.0s: kubectl describe pod ubuntu-random10g | tail -n 15                                         us-pil1-z1-bastion2: Fri Mar  1 04:49:09 2024

    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 60s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 60s
Events:
  Type     Reason          Age               From     Message
  ----     ------          ----              ----     -------
  Normal   AddedInterface  4m15s             multus   Add eth0 [10.245.6.62/32] from k8s-pod-network
  Normal   Pulling         4m15s             kubelet  Pulling image "penggu/ubuntu:random10G"
  Normal   Pulled          24s               kubelet  Successfully pulled image "penggu/ubuntu:random10G" in 3m50.078812682s (3m50.078824562s includ
ing waiting)
```
5. delete pods 
6. change registry image to private to ensure not pull from remote.
7. apply same pods to worker-node2 using 4m35s to pulling image
```
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 60s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 60s
Events:
  Type     Reason          Age                From     Message
  ----     ------          ----               ----     -------
  Normal   AddedInterface  5m48s              multus   Add eth0 [10.245.239.220/32] from k8s-pod-network
  Normal   Pulling         5m48s              kubelet  Pulling image "penggu/ubuntu:random10G"
  Normal   Pulled          72s                kubelet  Successfully pulled image "penggu/ubuntu:random10G" in 4m35.515593997s (4m35.515608107s inclu
ding waiting)
```

Logs on worker-nodes:
```
2024-03-01T04:51:42.998129723Z stderr F {"level":"info","ts":1709268702.9975944,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/penggu/ubuntu/manifests/random10G","status":200,"method":"HEAD","latency":0.004553897,"ip":"10.248.112.243","handler":"manifest"}
2024-03-01T04:51:43.012220162Z stderr F {"level":"info","ts":1709268703.0115528,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/penggu/ubuntu/manifests/sha256:5b5f28c83051d1583c7a940f73ea8746f14b51b4e43d6c68cb4e320cd915d577","status":200,"method":"GET","latency":0.002354699,"ip":"10.248.112.243","handler":"manifest"}
2024-03-01T04:51:43.030253891Z stderr F {"level":"info","ts":1709268703.0298615,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/penggu/ubuntu/blobs/sha256:4c2f1015f995970573934f75c783a2f0d267960c5e520bcdba91203ac483f4ba","status":200,"method":"GET","latency":0.004387315,"ip":"10.248.112.243","handler":"blob"}
2024-03-01T04:51:43.831344859Z stderr F {"level":"info","ts":1709268703.8309872,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/penggu/ubuntu/blobs/sha256:01007420e9b005dc14a8c8b0f996a2ad8e0d4af6c3d01e62f123be14fe48eec7","status":200,"method":"GET","latency":0.780460773,"ip":"10.248.112.243","handler":"blob"}
```

```
2024-03-01T04:51:42.994403226Z stderr F {"level":"info","ts":1709268702.9937582,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/penggu/ubuntu/manifests/random10G","status":200,"method":"HEAD","latency":0.012407902,"ip":"10.248.112.243","handler":"mirror"}
2024-03-01T04:51:43.007860677Z stderr F {"level":"info","ts":1709268703.0073617,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/penggu/ubuntu/manifests/sha256:5b5f28c83051d1583c7a940f73ea8746f14b51b4e43d6c68cb4e320cd915d577","status":200,"method":"GET","latency":0.006263951,"ip":"10.248.112.243","handler":"mirror"}
2024-03-01T04:51:43.026721411Z stderr F {"level":"info","ts":1709268703.0259619,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/penggu/ubuntu/blobs/sha256:4c2f1015f995970573934f75c783a2f0d267960c5e520bcdba91203ac483f4ba","status":200,"method":"GET","latency":0.009196026,"ip":"10.248.112.243","handler":"mirror"}
2024-03-01T04:51:43.827323623Z stderr F {"level":"info","ts":1709268703.8267856,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/penggu/ubuntu/blobs/sha256:01007420e9b005dc14a8c8b0f996a2ad8e0d4af6c3d01e62f123be14fe48eec7","status":200,"method":"GET","latency":0.785172872,"ip":"10.248.112.243","handler":"mirror"}
```

**Comment by phillebaba** [comment] 2024-03-01 10:15
It does not look like the issue is resolving peers, which is an issue I know exists that creates latency. I have been working on performance tests to verify potential solutions but I am not done with that yet.

If we assume that the latency is not in resolving peers we have to assume that the issue comes from blob transferring. This could be caused by networking limitations or disk io throughput on either side of the node.  What type of infrastructure are you running Spegel on? 

In the meantime I will try to think about a good standard for users to measure performance of image pulls.

**Comment by sonyafenge** [comment] 2024-03-01 18:04
we are using internal network and baremental to setup envirionement. If I run iperf between two nodes I can got below speed on both server and client:
```
iperf -c <ipaddress>

[ ID] Interval       Transfer     Bandwidth
[  1] 0.0000-10.0104 sec  24.4 GBytes  21.0 Gbits/sec
```

but if I use sepgel port, I got the result as below on iperf client and no respons on iperf server side:
```
iperf -c <ipaddress> -p 30020

------------------------------------------------------------
Client connecting to 10.248.113.13, TCP port 30020
TCP window size:  128 KByte (default)
------------------------------------------------------------
[  1] local 10.248.112.243 port 50228 connected with 10.248.113.13 port 30020
tcp write failed: Broken pipe
shutdown failed: Transport endpoint is not connected
[ ID] Interval       Transfer     Bandwidth
[  1] 0.0000-0.5104 sec  5.77 MBytes  94.8 Mbits/sec
```

**Closed** 2024-04-14 10:44 UTC
Labels: bug
